environmentFromSecret: ENC[AES256_GCM,data:xG0rNdVFERJstw==,iv:dN6x5xgfxVkWYOwhz66VvVa0qN2bu0X2QRvLuOFm6Os=,tag:wOHWZGA9V2QJQ8XGCx8Mcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-07T00:11:35Z"
    mac: ENC[AES256_GCM,data:gFM2bdajufVQgxLj8mZeycg2lQ+sxJ7FLiWXLZ5FqHX7bxNWeVgN8iFidff/1qSlV805gUbWBZqc/BdvOs+nAQcj0HDDqKs1WUXWsRY6c3q2K45BvHM4pY8g138QtpQb+m2m0OKLpfOdKc/s8eVcrYHLg/lAlmzAdT7Ew2FR2Mg=,iv:wf4PQJg1xdIcD3tY8cwmRO6QEbJQqkOZE9CGUQZdobY=,tag:w6eix4kyE5PuOD9iEEWYIw==,type:str]
    pgp:
        - created_at: "2022-12-07T00:11:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2FXXPYZNHmDAQwAmiVwIwYM7aYPmgXeZC6M6pZAqMb/Y/HyjxPt8C/6UVBd
            d2fy/pHsUsyJOYsulDct4uanHRjdIlfn6JS3O4o1XN6W2wuVooRitgovzd6cvEJq
            nPBexDFK44fgYUgQVkG0X9ihAvge1sSJRa2ms1zo73dr8aiX2bgFq/DHC5Nn5F9J
            ePZaYgD5IKhkRU2aeg3OWNYgJyRfIt/H5tKmDKN8O4XrBCQiTwDRcwXqfOJ2rmdX
            Gayy8Hx0X+Txzb3XFsTCE5SMJsi4zPbV2DffkdCEafW1m2TKfq/miDibDzEdmHdz
            RlRzv/4W7UPHqqstsaIhmQ0bfLj8ZfqQQeMF8eiVItevt+CPTe/gdUEhl5WgPfYv
            qebXGYMiDSZ3rM4L6De+9Fx3IhHWjNio373/F+Vd6mVrmNEf4I5RPaBLtA7gzWJy
            zfV4VG0vmWoISXg1i2+fXaQ3xkhmiM+otKvVnlyfvDIqDhG5HeNHrCAYubTxo1nd
            vN53MFZcCQl2rAWLjt8i0l4B6g+ql3CeXA6828+fbAv21x0eok9K8fUeDuigqVpa
            QhmyGViuy11Nfry65Tvtiy7j49LP3zVCM49ghQkK+0YiNL2oklXXLKIS+Q3Qrvh0
            9wp+/ILWuI0UsrSAztwz
            =yDC3
            -----END PGP MESSAGE-----
          fp: B9B71967F53C858E39D3102D57AEC788F1D5CB96
    unencrypted_suffix: _unencrypted
    version: 3.7.3
