apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: hello-world-app
